<?php include('includes/Header.phtml') ?>

<style>
.container {
	margin: 5em auto;
}
</style>


<div class="container">

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Person Bio</th>
    </tr>
  </thead>
  <tbody>
	  <?php foreach($employees as $employee) { ?>
    <tr>
      <th><?= $employee['id'] ?></th>
      <td><?= $employee['name'] ?></td>
      <td><?= $employee['age'] ?></td>
      <td><?= $employee['salary'] ?></td>
      <td><a href="person?id=<?= $employee['id'] ?>">Go to Bio</a></td>
	</tr>
	  <?php } ?>
  </tbody>
</table>

</div>


<?php include('includes/Footer.phtml') ?>