<?php include('includes/Header.phtml') ?>

<style>
.container {
	margin: 5em auto;
}
</style>


<div class="container">

<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-1"><?= $person['name'] ?></p>
      </div>
    </div>

    <div class="content">
		<h2>Age: <?= $person['age'] ?></h2>
		<h2>Salary: <?= $person['salary'] ?></h2>
    </div>
  </div>
</div>

</div>


<?php include('includes/Footer.phtml') ?>