<?php include('includes/Header.phtml') ?>

<style>
.container {
	margin: 5em auto;
}
</style>


<div class="container">

<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4">John Smith</p>
        <p class="subtitle is-6">@johnsmith</p>
      </div>
    </div>

    <div class="content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Phasellus nec iaculis mauris.
    </div>
  </div>
</div>

</div>


<?php include('includes/Footer.phtml') ?>