<!DOCTYPE html>
<html lang="en">

<head>
	<title>Employees</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css" />
</head>

<body>
	<nav class="navbar is-black" role="navigation" aria-label="main navigation">
		<div class="navbar-brand">
			<a class="navbar-item" style="color: whitesmoke; font-size: 1.5em;" href="/">
				Advanced PHP Activity 2
			</a>

			<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
				data-target="navbarBasicExample">
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
			</a>
		</div>

		<div id="main-nav" class="navbar-menu">
			<div class="navbar-end">
				<div class="navbar-item">
					<div class="buttons">
						<a class="button is-primary">
							<strong>Employee Home</strong>
						</a>
					</div>
				</div>
			</div>
		</div>
	</nav>